############################################################
### pathreat.analysis.sfa.aggregates.R ######################
### Area-weighted SFA aggregate diagnostics + slide macros ##
############################################################

rm(list = ls())
invisible(gc())

if (!file.exists("code/pathreat.analysis.config.R")) {
  stop("Run this script from the Pathreat project root.")
}

suppressMessages(source("code/pathreat.analysis.config.R"))

input_file <- paths$est_sfa
results_dir <- sub("/+$", "", paths$results_dir)
output_rds <- file.path(results_dir, "pathreat.sfa.aggregates.Rds")
output_csv <- file.path(results_dir, "pathreat.sfa.aggregates.csv")
output_tex <- "pub/tables/sfa.aggregates.macros.tex"

if (!file.exists(input_file)) {
  stop("Missing SFA results: ", input_file)
}

d_pa <- readRDS(input_file)

required_vars <- c(
  "wdpaid",
  "delta",
  "tc_protected",
  "frontier_level",
  "frontier",
  "u_hat",
  "size"
)

missing_vars <- setdiff(required_vars, names(d_pa))
if (length(missing_vars) > 0) {
  stop("Missing required SFA fields: ", paste(missing_vars, collapse = ", "))
}

if (any(!complete.cases(d_pa[, required_vars]))) {
  stop("The SFA aggregate sample contains missing required values.")
}

if (any(!is.finite(d_pa$size)) || any(d_pa$size <= 0)) {
  stop("PA area weights must be finite and strictly positive.")
}

if (anyDuplicated(d_pa$wdpaid)) {
  stop("The saved SFA results are not unique at the PA level.")
}

# Untruncated fitted residual around the estimated deterministic level frontier.
epsilon_hat <- d_pa$tc_protected - d_pa$frontier_level

# The saved level- and delta-space frontier representations must agree.
epsilon_delta_hat <- d_pa$delta - d_pa$frontier
if (max(abs(epsilon_hat - epsilon_delta_hat)) > 1e-10) {
  stop("Level- and delta-space SFA residuals are inconsistent.")
}

# A_p is WDPA GIS_AREA in km2, renamed to size upstream. These are source PA
# areas, not necessarily unique non-overlapping protected coverage.
total_pa_area <- sum(d_pa$size)
aggregate_achieved <- -sum(d_pa$size * d_pa$delta)
aggregate_underperformance <- sum(d_pa$size * d_pa$u_hat)
aggregate_total_potential <- aggregate_achieved + aggregate_underperformance

# When the saved control level is available, verify both representations of
# achieved threat reduction without making tc_control part of the core schema.
if ("tc_control" %in% names(d_pa)) {
  if (any(!is.finite(d_pa$tc_control))) {
    stop("Saved control threat levels must be finite when present.")
  }

  achieved_reduction <- d_pa$tc_control - d_pa$tc_protected
  if (max(abs(achieved_reduction + d_pa$delta)) > 1e-10) {
    stop("Control-minus-protected differences are inconsistent with delta.")
  }

  aggregate_achieved_from_levels <- sum(d_pa$size * achieved_reduction)
  if (!isTRUE(all.equal(
    aggregate_achieved,
    aggregate_achieved_from_levels,
    tolerance = 1e-12
  ))) {
    stop("Area-weighted achieved-reduction identities are inconsistent.")
  }
}

if (!is.finite(aggregate_total_potential) || aggregate_total_potential <= 0) {
  stop("The total potential threat reduction must be finite and positive.")
}

share_achieved <- aggregate_achieved / aggregate_total_potential
share_underperformance <- aggregate_underperformance / aggregate_total_potential
aggregate_net_residual <- sum(d_pa$size * epsilon_hat)
aggregate_positive_residual <- sum(d_pa$size * pmax(epsilon_hat, 0))

sfa_aggregates <- data.frame(
  n_pas = nrow(d_pa),
  total_pa_area_km2 = total_pa_area,
  aggregate_achieved_threat_reduction_threat_index_km2 = aggregate_achieved,
  aggregate_underperformance_threat_index_km2 = aggregate_underperformance,
  aggregate_total_potential_threat_reduction_threat_index_km2 =
    aggregate_total_potential,
  share_achieved = share_achieved,
  share_underperformance = share_underperformance,
  aggregate_net_residual_threat_index_km2 = aggregate_net_residual,
  aggregate_positive_residual_threat_index_km2 = aggregate_positive_residual,
  area_weighted_mean_underperformance = aggregate_underperformance / total_pa_area,
  area_weighted_mean_net_residual = aggregate_net_residual / total_pa_area,
  area_weighted_mean_positive_residual = aggregate_positive_residual / total_pa_area,
  median_underperformance = median(d_pa$u_hat),
  median_net_residual = median(epsilon_hat),
  share_negative_residual = mean(epsilon_hat < 0),
  stringsAsFactors = FALSE
)

saveRDS(sfa_aggregates, output_rds)
write.csv(sfa_aggregates, output_csv, row.names = FALSE)

fmt_fixed <- function(x, digits) {
  formatC(x, format = "f", digits = digits)
}

fmt_integer_tex <- function(x) {
  format(x, scientific = FALSE, big.mark = "{,}", trim = TRUE)
}

tex_macros <- c(
  "% Generated by code/pathreat.analysis.sfa.aggregates.R",
  paste0("\\newcommand{\\sfaAggregateNPAs}{",
         fmt_integer_tex(sfa_aggregates$n_pas), "}"),
  paste0("\\newcommand{\\sfaAggregateAreaMillions}{",
         fmt_fixed(sfa_aggregates$total_pa_area_km2 / 1e6, 3), "}"),
  paste0("\\newcommand{\\sfaAggregateAchievedThousands}{",
         fmt_fixed(aggregate_achieved / 1e3, 1), "}"),
  paste0("\\newcommand{\\sfaAggregateUnderperformanceThousands}{",
         fmt_fixed(
           sfa_aggregates$aggregate_underperformance_threat_index_km2 / 1e3,
           1
         ), "}"),
  paste0("\\newcommand{\\sfaAggregateTotalPotentialThousands}{",
         fmt_fixed(aggregate_total_potential / 1e3, 1), "}"),
  paste0("\\newcommand{\\sfaAchievedSharePercent}{",
         fmt_fixed(100 * sfa_aggregates$share_achieved, 1), "}"),
  paste0("\\newcommand{\\sfaUnderperformanceSharePercent}{",
         fmt_fixed(100 * sfa_aggregates$share_underperformance, 1), "}"),
  paste0("\\newcommand{\\sfaAggregateNetResidualThousands}{",
         fmt_fixed(
           sfa_aggregates$aggregate_net_residual_threat_index_km2 / 1e3,
           1
         ), "}"),
  paste0("\\newcommand{\\sfaAggregatePositiveResidualThousands}{",
         fmt_fixed(
           sfa_aggregates$aggregate_positive_residual_threat_index_km2 / 1e3,
           1
         ), "}"),
  paste0("\\newcommand{\\sfaAreaWeightedUnderperformance}{",
         fmt_fixed(sfa_aggregates$area_weighted_mean_underperformance, 4), "}"),
  paste0("\\newcommand{\\sfaAreaWeightedNetResidual}{",
         fmt_fixed(sfa_aggregates$area_weighted_mean_net_residual, 4), "}"),
  paste0("\\newcommand{\\sfaMedianUnderperformance}{",
         fmt_fixed(sfa_aggregates$median_underperformance, 3), "}"),
  paste0("\\newcommand{\\sfaMedianNetResidual}{",
         fmt_fixed(sfa_aggregates$median_net_residual, 3), "}"),
  paste0("\\newcommand{\\sfaNegativeResidualPercent}{",
         fmt_fixed(100 * sfa_aggregates$share_negative_residual, 1), "}")
)

writeLines(tex_macros, output_tex)

cat("SFA area-weighted aggregates\n")
cat(sprintf("  PAs: %s\n", format(nrow(d_pa), big.mark = ",")))
cat(sprintf("  Summed WDPA PA area: %.3f million km2\n", total_pa_area / 1e6))
cat(sprintf(
  "  Achieved threat reduction: %.3f x 10^3 threat-index km2 (%.1f%%)\n",
  aggregate_achieved / 1e3,
  100 * share_achieved
))
cat(sprintf(
  "  Estimated underperformance: %.3f x 10^3 threat-index km2 (%.1f%%)\n",
  aggregate_underperformance / 1e3,
  100 * share_underperformance
))
cat(sprintf(
  "  Total potential reduction:  %.3f x 10^3 threat-index km2\n",
  aggregate_total_potential / 1e3
))
cat(sprintf(
  "  Net frontier residual:      %.3f x 10^3 threat-index km2\n",
  aggregate_net_residual / 1e3
))
cat(sprintf(
  "  Positive frontier residual: %.3f x 10^3 threat-index km2\n",
  aggregate_positive_residual / 1e3
))
cat("Saved:", output_rds, "\n")
cat("Saved:", output_csv, "\n")
cat("Saved:", output_tex, "\n")
